---
- name: "show remote environment"
  shell: env
  vars:
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    - TYPEORM_MIGRATIONS_DIR: "./migrations"
    - TYPEORM_MIGRATIONS: "./migrations/*{.ts,.js}"
    - TYPEORM_ENTITIES: "./modules/domain/**/*.entity{.ts,.js}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

- name: "copy backend binaries"
  become: true
  synchronize:
    src: ../../backend
    dest: /home/ubuntu/udapeople
    recursive: true
    rsync_opts:
      - "--exclude=node_modules"

- name: "delete any running pm2 app"
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: "start server"
  become: true
  shell: |
    npm install
    npm run build

    ls
  args:
    chdir: /home/ubuntu/udapeople
