version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

executors:
  aws:
    docker:
      - image: amazon/aws-cli
  node:
    docker:
      - image: cimg/node:16.20.1
  python:
    docker:
      - image: python:3.10-alpine

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      when:
        type: string
      id:
        type: string
    steps:
      - run:
          name: Destroy backend CloudFormation stack
          command: |
            aws cloudformation delete-stack \
              --stack-name udapeople-be-<< parameters.id >> \
              --region us-east-1
          when: << parameters.when >>
      - run:
          name: Destroy frontend CloudFormation stack and S3 bucket
          command: |
            aws s3 rm s3://udapeople-bucket-<< parameters.id >> --recursive
            aws cloudformation delete-stack \
              --stack-name udapeople-fe-<< parameters.id >> \
              --region us-east-1
          when: << parameters.when >>

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      when:
        type: string
      id:
        type: string
    steps:
      - run:
          name: Revert migrations
          when: << parameters.when >>
          command: |
            SUCCESS=$(curl https://kvdb.io/D3pG2H4NNFFoc5px1FoE9L/migration_<< parameters.id >>)
            echo $SUCCESS
            if(( $SUCCESS ==1 )); 
            then
              npm run migrations:revert
            fi

jobs:

  build-frontend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: npm install
          working_directory: ./frontend
          command: npm install
      - run:
          name: npm run build
          working_directory: ./frontend
          command: npm run build
      - save_cache:
          key: build-frontend
          paths:
            - ./frontend/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - frontend/node_modules
            - frontend/dist

  build-backend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: npm install
          working_directory: ./backend
          command: npm install
      - run:
          name: build backend
          working_directory: ./backend
          command: |
            npm run build
      - save_cache:
          key: build-backend
          paths:
            - ./backend/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - backend/dist
            - backend/node_modules

  test-frontend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: build-frontend
      - run:
          name: Run tests with JUnit
          working_directory: ./frontend
          command: npm run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test_results
      - store_test_results:
          path: ./frontend/test_results
      - store_artifacts:
          path: ./frontend/test_results

  test-backend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys: [ build-backend ]
      - run:
          name: Run tests with JUnit
          working_directory: ./backend
          command: npm run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test_results
      - store_test_results:
          path: ./backend/test_results
      - store_artifacts:
          path: ./backend/test_results

  scan-frontend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys: [ build-frontend ]
      - run:
          name: Check Frontend against security vulnerabilities
          working_directory: ./frontend
          command: |
            set +e
            npm audit fix --audit-level=critical --force
            # run again if still not fixed
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

  scan-backend:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys: [ build-backend ]
      - run:
          name: scan backend against security vulnerabilities
          working_directory: ./backend
          command: |
            set +e
            npm audit fix --audit-level=critical --force
            # run again if still not fixed
            npm audit fix --audit-level=critical --force
            npm audit fix --audit-level=critical --force
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

  configure-infrastructure:
    executor: python
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "96:49:d4:d1:f4:af:c9:72:93:f1:9f:5a:ff:c3:a1:7e"
      - run:
          name: Install dependencies
          working_directory: ./.circleci/ansible
          command: |
            apk add --update ansible openssh-client
      - run:
          name: Config server
          working_directory: ./.circleci/ansible
          command: |
            echo "inventory.txt"
            cat inventory.txt
            ansible-playbook -i inventory.txt configure-server.yml
      - destroy-environment:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail

  deploy-infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Ensure back-end infrastructure exists
          working_directory: ./.circleci/files
          command: |
            aws cloudformation deploy \
              --template-file backend.yml \
              --region us-east-1 \
              --stack-name "udapeople-be-${CIRCLE_WORKFLOW_ID}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" \
              --tags project=udapeople-be-${CIRCLE_WORKFLOW_ID}
      - run:
          name: Save BACKEND_URL in KVDB
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=udapeople-be-${CIRCLE_WORKFLOW_ID}" \
              --output text)
            echo "backend ip: ${BACKEND_IP}"
            curl https://kvdb.io/D3pG2H4NNFFoc5px1FoE9L/BACKEND_URL -d "http://${BACKEND_IP}:3030"

      - run:
          name: Ensure front-end infrastructure exist
          working_directory: ./.circleci/files
          command: |
            aws cloudformation deploy \
              --region us-east-1 \
              --template-file frontend.yml \
              --stack-name "udapeople-fe-${CIRCLE_WORKFLOW_ID}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" \
              --tags project=udapeople-be-${CIRCLE_WORKFLOW_ID}

      - run:
          name: Add backend IP to ansible inventory
          working_directory: ./.circleci/ansible
          command: |
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=udapeople-be-${CIRCLE_WORKFLOW_ID}" \
              --output text >> inventory.txt
            cat inventory.txt
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/ansible/inventory.txt
      - destroy-environment:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail

  run-migrations:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: build-backend
      - run:
          name: Run migrations
          working_directory: ./backend
          command: |
            npm i
            sudo npm install pm2 -g
            echo ENVIRONMENT=production > ".env"
            echo TYPEORM_CONNECTION=postgres >> ".env"
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
            echo NODE_ENV=production >> ".env"
            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
            npm run migrations > migration.log
            cat migration.log
      - run:
          name: Send migration results to KVDB
          command: |
            echo "WorkflowID=${CIRCLE_WORKFLOW_ID}"
            if grep -c "executed successfully" migration.log
            then
              echo "Migration success, update kvdb"
              curl https://kvdb.io/D3pG2H4NNFFoc5px1FoE9L/migration_${CIRCLE_WORKFLOW_ID} -d '1'
            else
              echo "Migration failed"
              curl https://kvdb.io/D3pG2H4NNFFoc5px1FoE9L/migration_${CIRCLE_WORKFLOW_ID} -d '0'
            fi

      - revert-migrations:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail
      - destroy-environment:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail

  deploy-frontend:
    executor: aws
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install dependencies
          command: yum install -y tar gzip
      - attach_workspace:
          at: .
      - run:
          name: Get backend url
          command: |
            export BACKEND_URL=$(curl https://kvdb.io/D3pG2H4NNFFoc5px1FoE9L/BACKEND_URL)

            touch .env
            echo "${BACKEND_URL}" >> .env
            echo "backend url: ${BACKEND_URL}"
            echo ${CIRCLE_WORKFLOW_ID}
            echo "udapeople-${CIRCLE_WORKFLOW_ID}"
            echo "${BACKEND_URL}" >> frontend/.env
            cat frontend/.env
      - run:
          name: Deploy frontend objects
          working_directory: ./frontend
          command: |
            aws s3 cp ./dist "s3://udapeople-bucket-${CIRCLE_WORKFLOW_ID}" --recursive
      - persist_to_workspace:
          root: .
          paths:
            - frontend/dist
      - destroy-environment:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail
      - revert-migrations:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail

  deploy-backend:
    executor: python
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "96:49:d4:d1:f4:af:c9:72:93:f1:9f:5a:ff:c3:a1:7e"
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible aws-cli curl nodejs npm rsync openssh
      - run:
          name: Deploy backend
          working_directory: ./.circleci/ansible
          command: |
            ansible-playbook -i inventory.txt deploy-backend.yml -vv
      - destroy-environment:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail
      - revert-migrations:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail

  smoke-test:
    executor: aws
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Backend smoke test.
          command: |
            BACKEND_URL=$(curl https://kvdb.io/D3pG2H4NNFFoc5px1FoE9L/BACKEND_URL)
            echo "${BACKEND_URL}"
            curl "${BACKEND_URL}/api/status"
      - run:
          name: Frontend smoke test.
          command: |
            export URL="http://udapeople-bucket-${CIRCLE_WORKFLOW_ID}.s3.us-east-1.amazonaws.com/index.html"
            curl "${URL}"
      - destroy-environment:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail
      - revert-migrations:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail

  cloudfront-update:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: .
      - run:
          name: Update cloudfront distribution
          working_directory: ./.circleci/files
          command: |
            aws cloudformation deploy \
              --region us-east-1 \
              --template-file cloudfront.yml \
              --stack-name udapeople-cloudfront \
              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}" \
              --tags project=udapeople-cloudfront-${CIRCLE_WORKFLOW_ID}
      - revert-migrations:
          id: ${CIRCLE_WORKFLOW_ID}
          when: on_fail

  cleanup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Remove old stacks and files
          command: |
            export OldWorkflowID=$(curl https://kvdb.io/D3pG2H4NNFFoc5px1FoE9L/workflowid)
            export CurrentWorkflowID=${CIRCLE_WORKFLOW_ID}

            if [[ "$CurrentWorkflowID" != "$OldWorkflowID" ]]
            then
              aws s3 rm "s3://udapeople-bucket-${OldWorkflowID}" --recursive
              aws cloudformation delete-stack \
                --region us-east-1 \
                --stack-name "udapeople-fe-${OldWorkflowID}" \
              aws cloudformation delete-stack \
                --region us-east-1 \
                --stack-name "udapeople-be-${OldWorkflowID}"
            else
              echo "current workflow id: $OldWorkflowID. clean up not possible.
            fi

workflows:
  default:
    jobs:
      - build-backend
      - build-frontend
#      - test-frontend:
#          requires: [ build-frontend ]
#      - test-backend:
#          requires: [ build-backend ]
#      - scan-backend:
#          requires: [ build-backend ]
#      - scan-frontend:
#          requires: [ build-frontend ]
      - deploy-infrastructure:
          requires: [ build-backend, build-frontend ]
#          requires: [ test-frontend, test-backend, scan-frontend, scan-backend ]
          filters:
            branches:
              only: [ master ]
      - configure-infrastructure:
          requires: [ deploy-infrastructure ]
      - run-migrations:
          requires: [ configure-infrastructure ]
      - deploy-frontend:
          requires: [ run-migrations ]
      - deploy-backend:
          requires: [ run-migrations ]
#      - smoke-test:
#          requires: [ deploy-backend, deploy-frontend ]
#      - cloudfront-update:
#          requires: [ smoke-test ]
#      - cleanup:
#          requires: [ cloudfront-update ]