# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres:14.8"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glee
    ports:
      - "5432:5432"
