global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files
rule_files:
  - rules.yml

# Alerts
alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - 'localhost:9093'

# JOBS
scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['someip:9100']
