global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules.yml

# Alerts
alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - 'localhost:9093'

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['someip:9100']
