groups:
- name: Down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      summary: 'Instance is down'
      description: 'Job has been down for more than 1 minutes.'

- name: Usage
  rules:
    # Alert for any cluster that has average CPU idle < 50%
    - alert: HighUsage
      expr: avg(irate(node_cpu_seconds_total{mode="idle"}[1m]) * 100) < 50
      for: 1m
      annotations:
        summary: "High usage on {{ $labels.instance }}"
        description: "{{ $labels.instance }} has a average CPU idle (current value: {{ $value }}s)"
